"""
Enterprise Knowledge Assistant.

A retrieval-augmented question answering application. Users upload
documents, the application builds a searchable knowledge base, and
questions are answered strictly from the content of the uploaded
files.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import streamlit as st
from dotenv import load_dotenv

load_dotenv()

from modules.document_processor import (
    DocumentProcessingError,
    chunk_text,
    extract_text,
)
from modules.embeddings import EmbeddingModel
from modules.llm_handler import ContextChunk, LLMGenerationError, LLMHandler
from modules.vector_store import VectorStore

STORAGE_PATH = "./qdrant_storage"

st.set_page_config(
    page_title="Enterprise Knowledge Assistant",
    layout="wide",
    initial_sidebar_state="expanded",
)


def load_custom_styles() -> None:
    st.markdown(
        """
        <style>
        html, body, [class*="css"] {
            font-family: "Inter", "Segoe UI", sans-serif;
        }
        .main {
            background-color: #0F172A;
        }
        h1, h2, h3 {
            font-weight: 600;
            color: #E2E8F0;
        }
        p, span, label, div {
            color: #CBD5E1;
        }
        .app-subtitle {
            color: #94A3B8;
            font-size: 0.95rem;
            margin-bottom: 1.5rem;
        }
        .status-panel {
            background-color: #1E293B;
            border: 1px solid #334155;
            border-radius: 8px;
            padding: 0.9rem 1.1rem;
            margin-bottom: 0.75rem;
        }
        section[data-testid="stSidebar"] {
            background-color: #1E293B;
            border-right: 1px solid #334155;
        }
        section[data-testid="stSidebar"] * {
            color: #E2E8F0;
        }
        .stButton>button {
            border-radius: 6px;
            font-weight: 500;
            border: 1px solid #475569;
            background-color: #1E293B;
            color: #E2E8F0;
        }
        .stButton>button:hover {
            border-color: #2DD4BF;
            color: #2DD4BF;
        }
        .stChatMessage {
            border-radius: 8px;
            background-color: #1E293B;
        }
        [data-testid="stMetricValue"] {
            color: #2DD4BF;
        }
        .stTextInput input, .stFileUploader {
            background-color: #1E293B;
            color: #E2E8F0;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


@st.cache_resource(show_spinner=False)
def get_embedding_model() -> EmbeddingModel:
    return EmbeddingModel()


@st.cache_resource(show_spinner=False)
def get_llm_handler() -> LLMHandler:
    return LLMHandler()


@st.cache_resource(show_spinner=False)
def get_vector_store() -> VectorStore:
    return VectorStore(storage_path=STORAGE_PATH)


def initialize_session_state() -> None:
    if "messages" not in st.session_state:
        st.session_state.messages = []
    if "processed_files" not in st.session_state:
        st.session_state.processed_files = set()


def render_sidebar() -> None:
    with st.sidebar:
        st.markdown("### Model Information")
        st.caption("Responses are generated by a small language model running locally on this machine. No external API or account is required.")

        st.markdown("---")
        st.markdown("### Document Upload")
        st.caption("Processing documents replaces the current knowledge base. Upload all documents you want included together, or process them one set at a time.")
        uploaded_files = st.file_uploader(
            "Upload documents",
            type=["pdf", "docx", "txt"],
            accept_multiple_files=True,
        )

        process_clicked = st.button("Process Documents", use_container_width=True)

        st.markdown("---")
        st.markdown("### Knowledge Base")
        vector_store = get_vector_store()
        document_count = vector_store.document_count()
        st.metric("Indexed Chunks", document_count)

        if st.button("Clear Knowledge Base", use_container_width=True):
            vector_store.reset()
            st.session_state.processed_files = set()
            st.session_state.messages = []
            st.success("Knowledge base cleared successfully.")
            st.rerun()

    if process_clicked:
        handle_document_processing(uploaded_files)


def handle_document_processing(uploaded_files) -> None:
    if not uploaded_files:
        st.sidebar.warning("Please select at least one document to process.")
        return

    embedding_model = get_embedding_model()
    vector_store = get_vector_store()

    vector_store.reset()
    st.session_state.processed_files = set()
    st.session_state.messages = []

    new_files = uploaded_files
    progress = st.sidebar.progress(0, text="Processing uploaded files.")
    total_chunks_added = 0

    for idx, uploaded_file in enumerate(new_files, start=1):
        try:
            file_bytes = uploaded_file.read()
            text = extract_text(file_bytes, uploaded_file.name)

            if not text:
                st.sidebar.warning(f"No extractable text found in {uploaded_file.name}.")
                continue

            chunks = chunk_text(text, source=uploaded_file.name)
            if not chunks:
                continue

            progress.progress(
                min(idx / len(new_files), 1.0),
                text=f"Generating embeddings for {uploaded_file.name}.",
            )

            chunk_texts = [c.text for c in chunks]
            chunk_sources = [c.source for c in chunks]
            embeddings = embedding_model.encode(chunk_texts)

            added = vector_store.add_documents(chunk_texts, chunk_sources, embeddings)
            total_chunks_added += added
            st.session_state.processed_files.add(uploaded_file.name)

        except DocumentProcessingError as exc:
            st.sidebar.error(str(exc))

    progress.empty()

    if total_chunks_added > 0:
        st.sidebar.success(
            f"Processed {len(new_files)} document(s) and indexed {total_chunks_added} chunk(s)."
        )
    else:
        st.sidebar.warning("No new content was added to the knowledge base.")


def render_chat_interface() -> None:
    st.title("Enterprise Knowledge Assistant")
    st.markdown(
        '<div class="app-subtitle">Ask questions about your uploaded documents. '
        "Responses are generated strictly from the content of the knowledge base.</div>",
        unsafe_allow_html=True,
    )

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])
            if message.get("sources"):
                with st.expander("Sources"):
                    for source in message["sources"]:
                        st.markdown(f"- {source}")

    question = st.chat_input("Ask a question about your documents")
    if question:
        handle_question(question)


def handle_question(question: str) -> None:
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    vector_store = get_vector_store()

    with st.chat_message("assistant"):
        if vector_store.is_empty():
            answer = "No documents have been uploaded. Please upload at least one document."
            st.markdown(answer)
            st.session_state.messages.append({"role": "assistant", "content": answer})
            return

        with st.spinner("Searching knowledge base."):
            embedding_model = get_embedding_model()
            query_embedding = embedding_model.encode_single(question)
            results = vector_store.search(query_embedding, top_k=4)

        context_chunks = [ContextChunk(text=r.text, source=r.source) for r in results]
        sources = sorted({r.source for r in results})

        with st.spinner("Generating response."):
            try:
                llm_handler = get_llm_handler()
                answer = llm_handler.generate_answer(question, context_chunks)
            except LLMGenerationError as exc:
                answer = str(exc)

        st.markdown(answer)
        if sources:
            with st.expander("Sources"):
                for source in sources:
                    st.markdown(f"- {source}")

        st.session_state.messages.append(
            {"role": "assistant", "content": answer, "sources": sources}
        )


def main() -> None:
    load_custom_styles()
    initialize_session_state()
    render_sidebar()
    render_chat_interface()


if __name__ == "__main__":
    main()
